export const biharDistricts = {
  "Araria": ["Araria", "Bhargama", "Forbesganj", "Jokihat", "Kursakanta", "Narpatganj", "Palasi", "Raniganj", "Sikti"],
  "Arwal": ["Arwal", "Kaler", "Karpi", "Kurtha", "Sonbhadra Banshi Suryapur"],
  "Aurangabad": ["Aurangabad", "Barun", "Daudnagar", "Deo", "Goh", "Haspura", "Kutumba", "Madanpur", "Navinagar", "Obra", "Rafiganj"],
  "Banka": ["Amarpur", "Banka", "Barahat", "Belhar", "Bounsi", "Chandan", "Dhoraiya", "Fullidumar", "Katoriya", "Rajoun", "Shambhuganj"],
  "Begusarai": ["Bachhwara", "Bakhri", "Balia", "Barauni", "Begusarai", "Bhagwanpur", "Birpur", "Cheria Bariarpur", "Chhourahi", "Dandari", "Garhpura", "Khodabandpur", "Mansurchak", "Matihani", "Naokothi", "Sahebpur Kamal", "Shamho Akha Kurha", "Teghra"],
  "Bhagalpur": ["Bihpur", "Colgong", "Gopalpur", "Goradih", "Ismailpur", "Jagdishpur", "Kharik", "Nathnagar", "Navgachhia", "Pirpainti", "Rangra Chowk", "Sabour", "Sanhaula", "Shahkund", "Sultanganj"],
  "Bhojpur": ["Agiaon", "Ara", "Barhara", "Bihiya", "Charpokhari", "Garhani", "Jagdishpur", "Koilwar", "Piro", "Sahar", "Sandesh", "Shahpur", "Tarari", "Udwantnagar"],
  "Buxar": ["Brahmpur", "Buxar", "Chakki", "Chausa", "Chougain", "Dumraon", "Itarhi", "Kesath", "Nawanagar", "Rajpur", "Simri"],
  "Darbhanga": ["Alinagar", "Baheri", "Bahadurpur", "Biraul", "Darbhanga", "Ghanshyampur", "Gora Bauram", "Hanumannagar", "Hayaghat", "Jale", "Keoti", "Kiratpur", "Kusheshwar Asthan", "Kusheshwar Asthan East", "Manigachhi", "Singhwara", "Tardih"],
  "East Champaran": ["Adapur", "Areraj", "Banjaria", "Bankatwa", "Chakia", "Chiraia", "Dakshin Narkatiaganj", "Dhaka", "Ghorasahan", "Harsidhi", "Kalyanpur", "Kesaria", "Kotwa", "Madhuban", "Mehsi", "Motihari", "Narkatia", "Paharpur", "Pakridayal", "Patahi", "Phenhara", "Piprakothi", "Ramgarhwa", "Raxaul", "Sangrampur", "Tetaria"],
  "Gaya": ["Amas", "Atri", "Banke Bazar", "Barachatti", "Belaganj", "Bodh Gaya", "Dobhi", "Dumaria", "Fatehpur", "Gaya Town", "Guraru", "Gurua", "Imamganj", "Khizirsarai", "Konch", "Manpur", "Mohanpur", "Muhra", "Neem Chak Bathani", "Paraiya", "Sherghati", "Tekari", "Tikari", "Wazirganj"],
  "Gopalganj": ["Baikunthpur", "Barauli", "Bhorey", "Bijaipur", "Gopalganj", "Hathua", "Katiya", "Kuchaikote", "Manjha", "Pachrukhi", "Phulwaria", "Sidhwalia", "Thawe", "Uchkagaon"],
  "Jamui": ["Barhat", "Chakai", "Gidhaur", "Islamnagar Aliganj", "Jamui", "Jhajha", "Khaira", "Lakshmipur", "Sikandra", "Sono"],
  "Jehanabad": ["Ghosi", "Hulasganj", "Jehanabad", "Kako", "Makhdumpur", "Modanganj", "Ratni Faridpur"],
  "Kaimur": ["Adhaura", "Bhabua", "Bhagwanpur", "Chainpur", "Chand", "Durgawati", "Kudra", "Mohania", "Nuav", "Ramgarh", "Rohtas"],
  "Katihar": ["Amdabad", "Azamnagar", "Balrampur", "Barari", "Barsoi", "Dandkhora", "Falka", "Hasanganj", "Kadwa", "Katihar", "Korha", "Kursela", "Mansahi", "Manihari", "Pranpur", "Sameli"],
  "Khagaria": ["Alauli", "Beldaur", "Chautham", "Gogri", "Khagaria", "Mansi", "Parbatta"],
  "Kishanganj": ["Bahadurganj", "Dighalbank", "Kishanganj", "Kochadhaman", "Pothia", "Terhagachh", "Thakurganj"],
  "Lakhisarai": ["Barahiya", "Chanan", "Halsi", "Lakhisarai", "Pipariya", "Ramgarh Chowk", "Suryagarha"],
  "Madhepura": ["Alamnagar", "Bihariganj", "Chausa", "Ghelarh", "Gwalpara", "Kumarkhand", "Madhepura", "Murliganj", "Puraini", "Sankhuwa", "Singheshwar"],
  "Madhubani": ["Andhratharhi", "Babubarhi", "Basopatti", "Benipatti", "Bisfi", "Harlakhi", "Jainagar", "Jhanjharpur", "Kaluahi", "Khajauli", "Ladania", "Laukaha", "Laukahi", "Madhepur", "Madhubani", "Pandaul", "Phulparas", "Rajnagar"],
  "Munger": ["Asarganj", "Bariarpur", "Dharhara", "Haveli Kharagpur", "Jamalpur", "Munger", "Sadar", "Tarapur", "Tetiha Bamber"],
  "Muzaffarpur": ["Aurai", "Bandra", "Baruraj", "Bochahan", "Dholi", "Gaighat", "Kanti", "Katra", "Kurhani", "Marwan", "Minapur", "Motipur", "Muzaffarpur", "Mushahari", "Paroo", "Sahebganj", "Sakra"],
  "Nalanda": ["Asthawan", "Ben", "Biharsarif", "Bind", "Chandi", "Ekangarsarai", "Giriak", "Harnaut", "Hilsa", "Islampur", "Karai Parsurai", "Katrisarai", "Nagar Nausa", "Noorsarai", "Parbalpur", "Rahui", "Rajgir", "Sarmera", "Silao", "Tharthari"],
  "Nawada": ["Akbarpur", "Govindpur", "Hisua", "Kashchak", "Kawakol", "Meskaur", "Nardiganj", "Nawada", "Pakribarawan", "Rajauli", "Roh", "Sirdala", "Warisaliganj"],
  "Pashchim Champaran": ["Bagaha-1", "Bagaha-2", "Bairia", "Bettiah", "Bhitaha", "Chanpatia", "Gaunaha", "Jogapatti", "Lauriya", "Madhubani", "Mainatand", "Majhaulia", "Narkatiaganj", "Nautan", "Piprasi", "Ramnagar", "Sikta", "Thakrahan"],
  "Patna": ["Athmalgola", "Bakhtiarpur", "Barh", "Belchhi", "Bihta", "Bikram", "Daniawan", "Daniyawan", "Digha", "Dhanarua", "Dulhin Bazar", "Fatuha", "Ghoswari", "Khusrupur", "Maner", "Masaurhi", "Mokama", "Naubatpur", "Paliganj", "Pandarak", "Patna Sadar", "Phulwari Sharif", "Punarika", "Punpun", "Sampatchak"],
  "Purnia": ["Amour", "Baisa", "Baisi", "Banmankhi", "Barhara Kothi", "Bhawanipur", "Dagarua", "Dhamdaha", "Jalalgarh", "Kasba", "Krityanand Nagar", "Purnia East", "Rupauli", "Srinagar"],
  "Rohtas": ["Akorhi Gola", "Bikramganj", "Chenari", "Dawath", "Dehri", "Dinara", "Karakat", "Kargahar", "Kochas", "Nasriganj", "Nokha", "Rajpur", "Rohtas", "Sanjhauli", "Sasaram", "Sheosagar", "Surajpura", "Tilouthu"],
  "Saharsa": ["Banma Itahari", "Kahara", "Mahishi", "Nauhatta", "Patarghat", "Salkhua", "Satar Kataiya", "Saur Bazar", "Simri Bakhtiarpur", "Sonbarsa"],
  "Samastipur": ["Bibhutipur", "Bithan", "Dalsinghsarai", "Hasanpur", "Kalyanpur", "Khanpur", "Mohiuddinagar", "Morwa", "Patori", "Pusa", "Rosera", "Samastipur", "Sarairanjan", "Shivaji Nagar", "Singhia", "Tajpur", "Ujiarpur", "Vidyapati Nagar"],
  "Saran": ["Amnour", "Baniapur", "Chapra", "Dariyapur", "Dighwara", "Ekma", "Garkha", "Ishuapur", "Jalalpur", "Lahladpur", "Maker", "Manjhi", "Marhaura", "Mashrakh", "Nagra", "Panapur", "Parsa", "Revelganj", "Sonepur", "Taraiya"],
  "Sheikhpura": ["Ariyari", "Barbigha", "Chewara", "Ghatkusumbha", "Korma", "Sheikhpura", "Shekhopur Sarai"],
  "Sheohar": ["Dumri Katsari", "Piprahi", "Purnahiya", "Sheohar", "Tariani Chowk"],
  "Sitamarhi": ["Bairgania", "Bajpatti", "Bathnaha", "Belsand", "Bokhara", "Choraut", "Dumra", "Majorganj", "Nanpur", "Parihar", "Parsauni", "Pupri", "Rigoli", "Runnisaidpur", "Sonbarsa", "Sursand", "Suppi"],
  "Siwan": ["Andar", "Barharia", "Basantpur", "Bhagwanpur Hat", "Daraundha", "Darauli", "Goriakothi", "Guthani", "Hasan Pura", "Hussainganj", "Lakri Nabiganj", "Maharajganj", "Mairwa", "Nautan", "Pachrukhi", "Raghunathpur", "Siswan", "Siwan", "Ziradei"],
  "Supaul": ["Basantpur", "Chhatapur", "Kishanpur", "Marauna", "Nirmali", "Pipra", "Pratapganj", "Raghopur", "Saraigarh Bhaptiyahi", "Supaul", "Triveniganj"],
  "Vaishali": ["Bhagwanpur", "Bidupur", "Chehra Kalan", "Desari", "Garaul", "Hajipur", "Jandaha", "Lalganj", "Mahnar", "Mahua", "Patedhi Belsar", "Patepur", "Raghopur", "Rajapakar", "Sahdai Buzurg", "Vaishali"]
};

export const getBlocksForDistrict = (districtName: string): string[] => {
  return (biharDistricts as Record<string, string[]>)[districtName] || [];
};
